[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.setup]
script = [
'''
mkdir -p executables
rustup update
rustup target add thumbv7em-none-eabihf
'''
]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.place]
script = [
'''
echo "Placing binaries ..."
'''
]
